---
## pipeline stages:
# prep -> input + parse -> yield + proc
#
# prep          :: preprocess (stringify, and optional variable substitution)
#                   the block before parsing it.
# input + parse :: execute input directive.
# yield + proc  :: format output,
#                   perform variable substitution on formatted output,
#                   yield.

##
# format of a block
##
block:
  - yield: inputType  # this is a directive
    options: optVal
    args: {args dictionary}
    format: formatVal
    input: inputVal

##
# definition of schema elements
##
schema:
  # 'yield' : what to output (how to format output)
  yield:
    - text  # text: a list of newline-separated strings
    - dict  # a dictionary of key-value pairs
    - meta  # output nothing: set a metadata (substitution dictionary) variable

  # 'input' : where to source data
  inputType:
    # we can input everything we output (see 'yield' above)
    - text
    - dict
    - meta  # a key-value pair retrieved from substitutions dictionary
    # we can also input from other sources
    - file  # open a file on disk
    - eval  # python3 eval() statement
    - func  # import and then call call a function
    - exec  # subprocess execution (usually bash)

  inputVal: input_specific

  # substitution directives:
  # these are not mutually exclusive - a block may have both 'prep' and 'proc'
  format:
    - prep  # substitute values in block before parsing
    - proc  # substitute output after processing
  formatVal:
    - format  # use python str.format()
    - substitute  # use string.Template().substitute
    - safe_substitute  # use string.Template().safe_substitute

  # options : optional list of flags
  optVal:
    - json  # emit dictionary as JSON rather than YAML (the default)
...
